version: '3.6'

services:
  db:
    image: mysql:latest
    container_name: Full2020-086766
    environment:
      MYSQL_DATABASE: 'pfswcho'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'MDovbnych'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      netapp:
        ipv4_address: 10.0.10.3
  app:
    container_name: projectApp
    image: imerish/pfswchoproject
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/pfswcho
    networks:
      netapp:
        ipv4_address: 10.0.10.120

networks:
  netapp:
    name: Bridge−Zadanie−1
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.10.0/24